FROM ubuntu:20.04

RUN apt-get update && apt-get install -y apache2 && apte-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /var/www/html

COPY index.html .

CMD ["apache2ctl", "-D", "FOREGROUND"]

